#include<bits/stdc++.h>
#define ll long long
#define ld long double
using namespace std;
bool prime(int n){
	int m=sqrt(n);
	for(int i=2;i<=m;i++){
		if(n%i==0) return false;
	}
	return true;
}
string s;
int main(){
	ios::sync_with_stdio(false);
	cin.tie(0);
	cin>>s;
	if(s=="one") cout<<"1";
	else if(s=="two") cout<<"2";
	else if(s=="three") cout<<"3";
	else if(s=="four") cout<<"4";
	else if(s=="five") cout<<"5";
	else if(s=="six") cout<<"6";
	else if(s=="seven") cout<<"7";
	else if(s=="eight") cout<<"8";
	else if(s=="nine") cout<<"9";
	else if(s=="ten") cout<<"10";
	else if(s=="eleven") cout<<"11";
	else if(s=="twelve") cout<<"12";
	else if(s=="thirteen") cout<<"13";
	else if(s=="fourteen") cout<<"14";
	else if(s=="fifteen") cout<<"15";
	else if(s=="sixteen") cout<<"16";
	else if(s=="seventeen") cout<<"17";
	else if(s=="eighteen") cout<<"18";
	else if(s=="nineteen") cout<<"19";
	else if(s=="twenty") cout<<"20";
	else if(s=="twenty-one") cout<<"21";
	else if(s=="twenty-two") cout<<"22";
	else if(s=="twenty-three") cout<<"23";
	else if(s=="twenty-four") cout<<"24";
	else if(s=="twenty-five") cout<<"25";
	else if(s=="twenty-six") cout<<"26";
	else if(s=="twenty-seven") cout<<"27";
	else if(s=="twenty-eight") cout<<"28";
	else if(s=="twenty-nine") cout<<"29";
	else if(s=="thirty") cout<<"30";
	else if(s=="thirty-one") cout<<"31";
	else if(s=="thirty-two") cout<<"32";
	else if(s=="thirty-three") cout<<"33";
	else if(s=="thirty-four") cout<<"34";
	else if(s=="thirty-five") cout<<"35";
	else if(s=="thirty-six") cout<<"36";
	else if(s=="thirty-seven") cout<<"37";
	else if(s=="thirty-eight") cout<<"38";
	else if(s=="thirty-nine") cout<<"39";
	else if(s=="forty") cout<<"40";
	else if(s=="forty-one") cout<<"41";
	else if(s=="forty-two") cout<<"42";
	else if(s=="forty-three") cout<<"43";
	else if(s=="forty-four") cout<<"44";
	else if(s=="forty-five") cout<<"45";
	else if(s=="forty-six") cout<<"46";
	else if(s=="forty-seven") cout<<"47";
	else if(s=="forty-eight") cout<<"48";
	else if(s=="forty-nine") cout<<"49";
	else if(s=="fifty") cout<<"50";
	else if(s=="fifty-one") cout<<"51";
	else if(s=="fifty-two") cout<<"52";
	else if(s=="fifty-three") cout<<"53";
	else if(s=="fifty-four") cout<<"54";
	else if(s=="fifty-five") cout<<"55";
	else if(s=="fifty-six") cout<<"56";
	else if(s=="fifty-seven") cout<<"57";
	else if(s=="fifty-eight") cout<<"58";
	else if(s=="fifty-nine") cout<<"59";
	else if(s=="sixty") cout<<"60";
	else if(s=="sixty-one") cout<<"61";
	else if(s=="sixty-two") cout<<"62";
	else if(s=="sixty-three") cout<<"63";
	else if(s=="sixty-four") cout<<"64";
	else if(s=="sixty-five") cout<<"65";
	else if(s=="sixty-six") cout<<"66";
	else if(s=="sixty-seven") cout<<"67";
	else if(s=="sixty-eight") cout<<"68";
	else if(s=="sixty-nine") cout<<"69";
	else if(s=="seventy") cout<<"70";
	else if(s=="seventy-one") cout<<"71";
	else if(s=="seventy-two") cout<<"72";
	else if(s=="seventy-three") cout<<"73";
	else if(s=="seventy-four") cout<<"74";
	else if(s=="seventy-five") cout<<"75";
	else if(s=="seventy-six") cout<<"76";
	else if(s=="seventy-seven") cout<<"77";
	else if(s=="seventy-eight") cout<<"78";
	else if(s=="seventy-nine") cout<<"79";
	else if(s=="eighty") cout<<"80";
	else if(s=="eighty-one") cout<<"81";
	else if(s=="eighty-two") cout<<"82";
	else if(s=="eighty-three") cout<<"83";
	else if(s=="eighty-four") cout<<"84";
	else if(s=="eighty-five") cout<<"85";
	else if(s=="eighty-six") cout<<"86";
	else if(s=="eighty-seven") cout<<"87";
	else if(s=="eighty-eight") cout<<"88";
	else if(s=="eighty-nine") cout<<"89";
	else if(s=="ninety") cout<<"90";
	else if(s=="ninety-one") cout<<"91";
	else if(s=="ninety-two") cout<<"92";
	else if(s=="ninety-three") cout<<"93";
	else if(s=="ninety-four") cout<<"94";
	else if(s=="ninety-five") cout<<"95";
	else if(s=="ninety-six") cout<<"96";
	else if(s=="ninety-seven") cout<<"97";
	else if(s=="ninety-eight") cout<<"98";
	else if(s=="ninety-nine") cout<<"99";
	cout<<endl;
	return 0;
}

